### ISSUE TITLE
Request for sbl1 and abl upload

### ISSUE THREAD

**Issue by bkerler** [shinyquagsire23/Q710-SIGNhax-EL3-Warmboot#1]
Hi,
as the firmware doesn't seem to be available anywhere, can you please upload the sbl1 and aboot partitions for research ?

Thanks :)

**Comment by cloud1250x4** [comment]
looking very available here:

https://lg-firmwares.com/downloads-file/21490/Q710ULM20c_00_AMZ_US_OP_1121
